# Generated by Django 3.2.6 on 2021-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news_category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
