# Generated by Django 3.2.6 on 2021-10-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscomment_name_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='name_news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='news.news', verbose_name='Новость'),
        ),
    ]
