# Generated by Django 3.2.6 on 2021-08-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='citi',
            new_name='city',
        ),
    ]
