# Generated by Django 3.2.6 on 2021-09-04 09:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('post', models.CharField(max_length=30, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Наша специальность', 'verbose_name_plural': 'Наши специальности'},
        ),
    ]
