# Generated by Django 3.2.6 on 2021-09-05 07:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210904_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='static/images/portfolio', verbose_name='Аватарка')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('post', models.CharField(max_length=30, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Потфолио',
            },
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
