# Generated by Django 3.2.6 on 2021-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210905_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='post',
            field=models.CharField(choices=[('director', 'Директор'), ('zam_director', 'Заместитель Директора'), ('nachalnik_ceha', 'Начальник цеха'), ('injener', 'Инженер'), ('master', 'Мастер')], max_length=30, verbose_name='Должность'),
        ),
    ]
