# Generated by Django 3.2.6 on 2021-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_portfolio_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='lname',
            field=models.CharField(default='', max_length=20, verbose_name='Имя'),
        ),
    ]
