# Generated by Django 3.2.6 on 2021-09-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210905_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
