# Generated by Django 3.2.6 on 2021-09-06 20:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=25, verbose_name='Название сайта')),
                ('email_header', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phoneheader', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Настройки Header',
                'verbose_name_plural': 'Настройки Header',
            },
        ),
    ]
