# Generated by Django 3.2.6 on 2021-09-07 17:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_settingsheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheader',
            name='fb_url',
            field=models.CharField(default='', max_length=25, verbose_name='Ссылка на facebook'),
        ),
        migrations.AddField(
            model_name='settingsheader',
            name='image_Header',
            field=models.ImageField(default='', upload_to='static/images', verbose_name='Баннер Верхний'),
        ),
        migrations.AddField(
            model_name='settingsheader',
            name='inst_url',
            field=models.CharField(default='', max_length=25, verbose_name='Ссылка на instagram'),
        ),
        migrations.AddField(
            model_name='settingsheader',
            name='ld_url',
            field=models.CharField(default='', max_length=25, verbose_name='Ссылка на linkedin'),
        ),
        migrations.AddField(
            model_name='settingsheader',
            name='tw_url',
            field=models.CharField(default='', max_length=25, verbose_name='Ссылка на twitter'),
        ),
        migrations.AlterField(
            model_name='settingsheader',
            name='email_header',
            field=models.EmailField(default='', max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='settingsheader',
            name='name_site',
            field=models.CharField(default='', max_length=25, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='settingsheader',
            name='phoneheader',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
