# Generated by Django 3.2.6 on 2021-09-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210907_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
