# Generated by Django 3.2.6 on 2021-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
