# Generated by Django 3.2.6 on 2021-09-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210914_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsHeader',
        ),
    ]
