# Generated by Django 3.2.6 on 2021-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_settingsheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='city',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
