# Generated by Django 3.2.6 on 2021-09-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210918_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
