# Generated by Django 3.2.6 on 2021-09-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
