# Generated by Django 3.2.6 on 2021-11-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0020_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('content', models.TextField(blank=True, verbose_name='Описание, местоположение')),
            ],
            options={
                'verbose_name': 'Категория рекламы',
                'verbose_name_plural': 'Категории рекламы',
            },
        ),
        migrations.CreateModel(
            name='ReklamaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='static/recklama/banner/%Y/%m/%d/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(verbose_name='Дата окончания публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('lname', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('reklama_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.reklamacategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
                'ordering': ['time_create', 'name'],
            },
        ),
    ]
