# Generated by Django 3.2.6 on 2021-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_reklamacategory_reklamapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklamapost',
            name='is_published',
            field=models.BooleanField(verbose_name='Опубликовано'),
        ),
    ]
