# Generated by Django 3.2.6 on 2021-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_reklamapost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklamapost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
