# Generated by Django 3.2.6 on 2021-09-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Организация')),
                ('is_job', models.BooleanField(default=True, verbose_name='Договор')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=100, verbose_name='Роль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=100, verbose_name='Объект')),
                ('oblast', models.CharField(max_length=100, verbose_name='Область')),
                ('sity', models.CharField(max_length=100, verbose_name='Город или район')),
                ('address', models.CharField(max_length=100, verbose_name='адрес, улица, дом.')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя ответственного на объекте')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Контактный телефон')),
                ('name_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.entity', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('message', models.TextField(help_text='Подробно опишите проблему', verbose_name='Сообщение')),
                ('promptness', models.CharField(choices=[('fast', 'Срочно'), ('medium', 'Среднее'), ('no_rush', 'Не срочно')], max_length=50, verbose_name='Срочность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения заявки')),
                ('name_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.subject', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('post', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('login', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Login')),
                ('name_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.role', verbose_name='Роль')),
            ],
        ),
    ]
