# Generated by Django 3.2.6 on 2021-09-19 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210919_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='login',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидает'), ('accepted', 'Принята'), ('completed', 'Выполнена')], default='wait', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
