# Generated by Django 3.2.6 on 2021-09-19 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20210919_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='login',
        ),
        migrations.AddField(
            model_name='service',
            name='login',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.AddField(
            model_name='profile',
            name='login',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='service',
            name='promptness',
            field=models.CharField(choices=[('Срочно', 'Срочно'), ('Среднее', 'Среднее'), ('Не срочно', 'Не срочно')], max_length=50, verbose_name='Срочность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Ожидает', 'Ожидает'), ('Принята', 'Принята'), ('Выполнена', 'Выполнена')], default='wait', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.entity', verbose_name='Организация'),
        ),
    ]
