# Generated by Django 3.2.6 on 2021-09-22 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20210919_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firm',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.entity', verbose_name='фирма'),
        ),
        migrations.AddField(
            model_name='service',
            name='id_usr',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
