# Generated by Django 3.2.6 on 2021-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_firm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='id_usr',
            new_name='id_user',
        ),
    ]
