# Generated by Django 3.2.6 on 2021-10-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_service_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id_user',
        ),
    ]
