# Generated by Django 3.2.6 on 2021-10-10 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_service_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=220, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
