# Generated by Django 3.2.6 on 2021-10-12 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/avatars/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
