# Generated by Django 3.2.6 on 2021-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_feedback_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text=' ', max_length=254, verbose_name='Почта'),
        ),
    ]
