# Generated by Django 3.2.6 on 2021-09-19 13:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_contact_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text=' ', max_length=254, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Полное Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
