# Generated by Django 3.2.6 on 2021-09-28 18:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование должности')),
                ('text', models.TextField(verbose_name='Функциональные обязанности')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='static/images/portfolio', verbose_name='Аватарка')),
                ('lname', models.CharField(default='', max_length=20, verbose_name='Имя')),
                ('fname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Информация')),
                ('is_jobs', models.BooleanField(default=True, verbose_name='Работает')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.category_portfolio', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Потфолио',
            },
        ),
    ]
