# Generated by Django 3.2.6 on 2021-09-05 11:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='static/images/portfolio', verbose_name='Аватарка')),
                ('lname', models.CharField(default='', max_length=20, verbose_name='Имя')),
                ('fname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('post', models.CharField(choices=[('director', 'Директор'), ('zam_director', 'Заместитель Директора'), ('nachalnik_ceha', 'Начальник цеха'), ('injener', 'Инженер'), ('master', 'Мастер')], max_length=30, verbose_name='Должность')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Почта')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Потфолио',
            },
        ),
    ]
