# Generated by Django 3.2.6 on 2021-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avatar',
            field=models.ImageField(upload_to='static/images/portfolio/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
