# Generated by Django 3.2.6 on 2021-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование должности')),
                ('text', models.TextField(verbose_name='Функциональные обязанности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='post',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
    ]
