# Generated by Django 3.2.6 on 2021-09-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210909_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.category_portfolio', verbose_name='Должность'),
        ),
    ]
