# Generated by Django 3.2.6 on 2021-09-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
